Feature/95/create sponsor section and styling
LaurierHawkHacks/Landing pull request #118
Opened 2024-02-23 05:13 UTC by AmirAgassi

🤝[Create Sponsor Section and Styling #95](https://github.com/LaurierHawkHacks/Landing/issues/95)

🔍 **What's Included**
- Added new Sponsor section in `Sponsor.section.tsx`.
- Integrated Sponsor section into the landing page in `Landing.tsx`.
- Included new assets for sponsor and partner logos in the `src/assets/logos` directory.
- Updated `index.tsx` to export the new `SponsorSection`.

📁 Files Affected:
- `src/assets/logos/*`
- `src/assets/sponsor/*`
- `src/components/sections/Sponsor.section.tsx`
- `src/components/index.tsx`
- `src/pages/Landing.tsx`

2024-02-24 21:37 UTC, juancwu requested changes

2024-02-24 21:37 UTC, juancwu commented on src/components/sections/Sponsor.section.tsx
> +        <section className="sponsor-section relative" style={{ position: 'relative', zIndex: '2' }}>
```suggestion
        <section className="sponsor-section relative z-[2]">
```

2024-02-24 21:37 UTC, juancwu commented
Was the head of the bird cut off on purpose?

2024-02-25 02:40 UTC, AmirAgassi commented
> Was the head of the bird cut off on purpose?

Yup, both here and on the contact section, there's a section/footer above and below them that the bird's supposed to clip into in a prod environment. The bird uses absolute positioning as to not mess up any sections above/below it with a huge space.

(I just add the section twice in `Landing.tsx` to add stuff above/below, so I can make sure it actually works lol)

2024-03-04 04:24 UTC, juancwu approved these changes

2024-03-04 04:25 UTC, juancwu commented
Just need to resolve the merge conflicts.

2024-03-11 21:21 UTC, juancwu approved these changes

2024-03-11 21:21 UTC, merged