Setup-Typography
LaurierHawkHacks/Landing pull request #41
Opened 2023-11-23 00:04 UTC by ABCodez

- Added font families to index.css / tailwind.config.mjs
- Setup global font style
- Setup font styles for h1, h2, h3, p, span tags

fixes #34

2023-11-23 00:25 UTC, aidantrabs commented on index.html
>  		<link rel="preconnect" href="https://fonts.googleapis.com" />
Also don't think these lines are necessary, otherwise looks good to me

2023-11-23 23:32 UTC, juancwu approved these changes

2023-11-24 20:41 UTC, aidantrabs requested changes

2023-11-25 02:57 UTC, ABCodez commented on index.html
> +
Resolved in latest commit

2023-11-25 22:09 UTC, merged